// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package db

import (
	"context"
)

type Querier interface {
	CreateEducation(ctx context.Context, arg CreateEducationParams) (Education, error)
	CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error)
	DeleteAuthor(ctx context.Context, id int32) error
	DeleteEducation(ctx context.Context, id int32) error
	GetEducations(ctx context.Context) ([]Education, error)
	GetProjects(ctx context.Context) ([]Project, error)
	GetUser(ctx context.Context, login string) (Admin, error)
}

var _ Querier = (*Queries)(nil)
