// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0
// source: user.sql

package db

import (
	"context"
)

const getUser = `-- name: GetUser :one
SELECT login, password
FROM admin
WHERE login = $1
LIMIT 1
`

func (q *Queries) GetUser(ctx context.Context, login string) (Admin, error) {
	row := q.db.QueryRowContext(ctx, getUser, login)
	var i Admin
	err := row.Scan(&i.Login, &i.Password)
	return i, err
}
